name: Publish/Deploy Post Merge
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number, used for manual run of workflow in the event of an error'
        required: true

jobs:
  publish-deploy-post-merge:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout HEAD
        uses: actions/checkout@v3
